config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :goals, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :title, :description, :user, :completed, :privacy, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6 }, allow_nil: true
  validates :username, :session_token, uniqueness: true

  attr_reader :password
  after_initialize :ensure_session_token


  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end


  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end


  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find_by(session_token: session[:session_token])
  end
  def log_in(user)
    session[:session_token]= user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_log_in
    redirect_to new_session_url unless current_user
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash[:errors] = @goal.errors.full_messages
      # render :new
      redirect_to new_goal_url
    end
  end

  def new
    @goal = Goal.new
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_url
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.user_id = current_user.id
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :completed, :privacy)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      log_in(@user)
      redirect_to goals_url
    else
      flash[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def new
    render :new
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    user = User.new(user_params)
    if user.save
      log_in(user)
      redirect_to goals_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
  <label>Title
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>

  <label>Description
    <input type="text" name="goal[description]" value="<%= @goal.description %>">
  </label>

  <label>Completed?
   <select name="goal[completed]">
     <option value="completed" (@goal.completed ? "selected" : "")>Completed</option>
     <option value="incomplete" (!@goal.completed ? "selected" : "")>Incomplete</option>
   </select>
  </label>

  <label>Private?
    <input type="checkbox" name="goal[privacy]" <%= 'checked' if @goal.privacy %>>
  </label>


  <input type="submit" value="Edit Goal">
</form>

app/views/goals/index.html.erb
<h1>All Goals</h1>

app/views/goals/new.html.erb
<h1>Create Goal</h1>

<form action="<%= goals_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
  <label>Title
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>

  <label>Description
    <input type="text" name="goal[description]" value="<%= @goal.description %>">
  </label>

  <label>Completed?
   <select name="goal[completed]">
     <option value="completed">Completed</option>
     <option value="incomplete">Incomplete</option>
   </select>
  </label>

  <label>Private?
    <input type="checkbox" name="goal[privacy]" <%= 'checked' if @goal.privacy %>>
  </label>


  <input type="submit" value="Create Goal">
</form>

app/views/goals/show.html.erb
<h1> <%= @goal.title %> </h1>
<h3> <%= @goal.description %> </h3>

<%= button_to "Delete Goal", goal_url(@goal), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= flash[:errors] %>


    <% if current_user %>
      <%= current_user.username  %>
      <%= button_to "Sign Out", session_url, method: :delete %>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">

  <label>Username
    <input type="text" name="user[username]">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>